# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GbfsSystem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, url=None):  # noqa: E501
        """GbfsSystem - a model defined in OpenAPI

        :param id: The id of this GbfsSystem.  # noqa: E501
        :type id: str
        :param name: The name of this GbfsSystem.  # noqa: E501
        :type name: str
        :param url: The url of this GbfsSystem.  # noqa: E501
        :type url: str
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'url': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'url': 'url'
        }

        self._id = id
        self._name = name
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'GbfsSystem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The gbfs_system of this GbfsSystem.  # noqa: E501
        :rtype: GbfsSystem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this GbfsSystem.


        :return: The id of this GbfsSystem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GbfsSystem.


        :param id: The id of this GbfsSystem.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this GbfsSystem.

        Name of the GBFS System  # noqa: E501

        :return: The name of this GbfsSystem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GbfsSystem.

        Name of the GBFS System  # noqa: E501

        :param name: The name of this GbfsSystem.
        :type name: str
        """
        if name is not None and len(name) > 256:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `256`")  # noqa: E501

        self._name = name

    @property
    def url(self):
        """Gets the url of this GbfsSystem.

        URL to the gbfs.json file of the GBFS System, containing all the accesible URLs  # noqa: E501

        :return: The url of this GbfsSystem.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this GbfsSystem.

        URL to the gbfs.json file of the GBFS System, containing all the accesible URLs  # noqa: E501

        :param url: The url of this GbfsSystem.
        :type url: str
        """

        self._url = url
